### ISSUE TITLE
Autowareanalyse

### ISSUE THREAD

**Issue by luk-ha** [ll7/psaf2#22]
https://github.com/Autoware-AI/autoware.ai

Ziel: Aufwandsabschätzung was man davon mit wie viel Aufwand sinnvoll verwenden könnte

**Comment by faeibson** [comment]
Dokumentation und Hilfe
Wiki auf GitHub: https://github.com/Autoware-AI/autoware.ai/wiki
ROS Answers: https://answers.ros.org/questions/scope:all/sort:activity-desc/tags:autoware/page:1/
ROS Discourse: https://discourse.ros.org/c/autoware/46
Autoware Manuals: https://github.com/CPFL/Autoware-Manuals/tree/master/en (Quick Start, User's Manual, ..)

--> Introduction to CARLA Simulator using Autoware: https://www.youtube.com/watch?v=Z7PLkcY9Mtk

Autoware -> Localization, Object detetion, Driving control, 3D map generation and sharing

CARLA <-> ROS Bridge <-> Carla Autoware Bridge <-> Autoware

Carla TF / Sensor + Path -> Autoware -> Carla Vehicle Control
Map: Lanelet2 / Point Cloud Map (Tier4 Map Tools: https://tools.tier4.jp/)

OpenPlanner + Autoware: https://www.youtube.com/watch?v=BS5nLtBsXPE

Deep neural Yolo image detector package: https://autoware.readthedocs.io/en/feature-documentation_rtd/DevelopersGuide/PackagesAPI/detection/vision_darknet_detect.html

**Comment by faeibson** [comment]
erfolglos abgehakt.
