### ISSUE TITLE
Überblick Trajektorienverfolgungsregler

### ISSUE THREAD

**Issue by luk-ha** [ll7/psaf2#24]
z.B. LQR, Pure Pursuit Regler, Model Predictive and Steering Control
https://github.com/AtsushiSakai/PythonRobotics
ttps://github.com/RobeSafe-UAH/Waypoint_Tracking_Controller

DoD: Empfehlung für unsere Trajektorienplanung/regelung

**Comment by halentin** [comment]
Ich habe einen Wiki-Eintrag zu den gängigen Path-Tracking-Algorithmen geschrieben:
https://github.com/ll7/psaf2/wiki/Path-Tracking-Algorithmen

Mein Vorschlag für unsere Implementierung wäre die Stanley-Methode, zu der unter https://github.com/AtsushiSakai/PythonRobotics auch eine Beispielimplementierung existiert. 
Konkret benötigt werden dafür folgende Daten:
*Position, Geschwindigkeit und Heading des Ego-Cars
*nächstgelegener Punkt auf dem Pfad
*die Richtung (Ableitung) des Pfades an diesem Punkt

Eine perfekte(womöglich illegale) Lösung für das Pfadverfolgungsproblem könnten wir wohl erreichen, wenn wir den Model-Predictive Ansatz verfolgen würden, und als Modell das Fahrzeugkinematikmodell von CARLA einsetzen ;)
