### ISSUE TITLE
Erkennung von Ampeln

### ISSUE THREAD

**Issue by yuk13** [ll7/psaf2#34]

**Comment by yuk13** [comment]
Ampeln sind Akteure in CARLA
![image](https://user-images.githubusercontent.com/74297094/102938220-2d4cbe80-44ac-11eb-82e1-a5959f718732.png)
![image](https://user-images.githubusercontent.com/74297094/102938266-448bac00-44ac-11eb-8494-e9a4bd21fd62.png)

TrafficLightsSensor: ein Sensor, der den Status aller Ampeln anzeigt

**Comment by halentin** [comment]
neue DoD:
die Informationen aus dem Ampelsensor sollen sinnvoll (zB) als Topic bereitgestellt werden
Es soll auch beachtet werden, ob sich die Ampeln tatsächlich auf dem Global Path befinden
